repos:
-   repo: local
    hooks:
    -   id: requirements
        name: requirements
        entry: pip freeze > requirements.txt
        language: system
        pass_filenames: false
        always_run: true